name: Manually Run E2E Tests

on:
  workflow_dispatch:

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: use node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'

      - name: install dependencies
        run: yarn install --with-deps --frozen-lockfile

      - name: run e2e tests
        run: yarn test:e2e

      - name: upload test results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-e2e-report
          path: playwright-report/
          retention-days: 30
